//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSocial.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportePromotor
    {
        public long Id_Promotor { get; set; }
        public string Nombre_Promotor { get; set; }
        public string Apellido_Promotor { get; set; }
        public string Telefono_Promotor { get; set; }
        public string Direccion_Promotor { get; set; }
        public string Nombre_Zona { get; set; }
        public string Nombre_Proyecto { get; set; }
        public string Nombre_Actividad { get; set; }
        public string Fecha_Actividad { get; set; }
        public string Nombre_ADESCO { get; set; }
    }
}
